spring:
  application:
    name: coj-backend
  datasource:
    url: jdbc:mysql://localhost:3306/coj?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: tao072500
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10